data_path: /home/Dataset/fastMRI/
default_root_dir: /home/wang1711/project/PDAC/
gpus: 2
batch_size: 1

num_list: [48, 192, 288, 320, 336, 352, 364, 376, 384]   #  coarse-to-fine interval for 8x acceleration, start from 384/8=48

# dataset setting
accelerations:
- 8
center_fractions:
- 0.04
challenge: multicoil
check_val_every_n_epoch: 1
combine_train_val: False
mask_type: random

# training setting
lr: 0.0001
lr_gamma: 0.1
lr_step_size: 45
weight_decay: 0.0
max_epochs: 50

# model setting
num_cascades: 8
resume_from_checkpoint: null
seed: 42
sens_chans: 16
uniform_train_resolution:
- 384
- 384
volume_sample_rate: 1.0
embed_dim: 66
patch_size: 1
window_size: 8
depths: 
- 2
- 2
- 2
num_heads:
- 3
- 6
- 12
mlp_ratio: 2.0
resi_connection: 1conv
bottleneck_depth: 2
bottleneck_heads: 24
conv_downsample_first: True
num_adj_slices: 1
verbose: True
use_checkpointing: True