data_path: /home/Dataset/fastMRI/
default_root_dir: ./experiments/fastmri_pdac/singlecoil
resume_from: null

gpus: 1
batch_size: 2

# degradation budget schedule for pdac iterations
num_list: [40, 160, 240, 264, 280, 292, 304, 312, 320]   #  coarse-to-fine interval for 8x acceleration, start from 384/8=48
# num_list: [80, 160, 240, 264, 280, 292, 304, 312, 320]   #  coarse-to-fine interval for 4x acceleration, start from 320/4=80

# dataset setting
accelerations:
- 8
center_fractions:
- 0.04
challenge: singlecoil
check_val_every_n_epoch: 1
combine_train_val: False
mask_type: random

# training setting
lr: 0.0001
lr_gamma: 0.1
lr_step_size: 35
weight_decay: 0.0
max_epochs: 40

# model setting
num_cascades: 8
resume_from_checkpoint: null
seed: 42
sens_chans: 16
uniform_train_resolution:
- 320
- 320
volume_sample_rate: 1.0
embed_dim: 66
patch_size: 1
window_size: 4
depths: 
- 2
- 2
- 2
num_heads:
- 3
- 6
- 12
mlp_ratio: 2.0
resi_connection: 1conv
bottleneck_depth: 2
bottleneck_heads: 24
conv_downsample_first: True
num_adj_slices: 1
verbose: True
use_checkpointing: True